### ISSUE TITLE
which is correct checkpoint for inference ? 

### ISSUE THREAD

**Issue by kelisiya** [Cheeun/CADyQ#1]
It's a nice work for SR ! But when I run test_cadyq_image.sh and student_weights for your checkpoint , all have missing key error .

**Comment by Cheeun** [comment]
Hello, thanks for your interest in our work!
Sorry for the inconvenience.
The previously uploaded student&teacher weights are for training.
I have newly uploaded the pretrained cadyq weights for inference in [Google Drive](https://drive.google.com/drive/folders/1pkbG4bQG6CoTxJKrUnBAEOxeQVUzvAsp?usp=sharing).

**Comment by kelisiya** [comment]
> Hello, thanks for your interest in our work! Sorry for the inconvenience. The previously uploaded student&teacher weights are for training. I have newly uploaded the pretrained cadyq weights for inference in [Google Drive](https://drive.google.com/drive/folders/1pkbG4bQG6CoTxJKrUnBAEOxeQVUzvAsp?usp=sharing).

Thanks!
