### ISSUE TITLE
I want to inference my own image . 

### ISSUE THREAD

**Issue by kelisiya** [Cheeun/CADyQ#2]
Now I want to inference my image in your model . I want to trace your model when I set args.fully is True  , there is `AttributeError: module 'model.carn_pams' has no attribute 'PAMS_BasicBlock' . But when I run test.py it's ok .
`

**Comment by Cheeun** [comment]
Thanks for your interest!

If you would like to inference your own image with our checkpoints, you should set **args.fully as False**. args.fully was the option to fully quantize all the modules of the baseline SR model and currently our checkpoints are from the models that only the high-level feature extraction module is quantized. 

(Our paper, following previous works on SR quantization, quantizes weights and feature maps in the layers of the high-level feature extraction module, where most of the costly operations are concentrated in.)

Hope this answers your question!
