### ISSUE TITLE
Hardware support for inference

### ISSUE THREAD

**Issue by Sheldon04** [Cheeun/CADyQ#4]
Hi, it is not mentioned in the paper that how to implement the NVIDIA support for the quantized model to inference. Could you please give some explanations? Thks very much!

**Comment by Cheeun** [comment]
Thanks for your interest in our work and sorry for the delayed answer!
Similar to [HAQ](https://github.com/mit-han-lab/haq) that utilizes the latency lookup table, we calculate our latency for each image by combining each convolutional layer’s latency (and also that of the bit selector network). You can refer to this [project](https://github.com/Zhen-Dong/HAWQ/blob/main/tvm_benchmark/README.md) for details on measuring each convolutional layer’s latency for the selected bit-widths.
