### ISSUE TITLE
Questions about FQR

### ISSUE THREAD

**Issue by hltechl** [Cheeun/CADyQ#5]
Hi, i have some questions about FQR!

Are avg_bit and FQR the same thing?
Does FQR only consider the residual blocks? 
Aren't you considering the 1x1 conv inside the CARN?

Could you please give some explanations? 
Thank you very much

**Comment by Cheeun** [comment]
Hi, thanks for your interest in our work!
FQR is the average bit-width for the quantized convolutions for the feature extraction stage. 1x1 convolutions in CARN are not quantized and hence excluded from FQR calculation.
Hope this answers your question!
