### ISSUE TITLE
Wonderful work！But its markdown doesn't contain a file named 'div2k_valid'. Can you add a Google Link To It？Thanks

### ISSUE THREAD

**Issue by dunanyang** [Cheeun/CADyQ#8]

**Comment by Cheeun** [comment]
Thanks for your interest in our work and sorry for the inconvenience.
DIV2K_valid can be downloaded in the following link: [DIV2K](https://data.vision.ee.ethz.ch/cvl/DIV2K/).

**Comment by dunanyang** [comment]
Thanks very much! (Fortunately, I have handled those problems before.)
