### ISSUE TITLE
Error(s) in loading state_dict for CARN_CADyQ:

### ISSUE THREAD

**Issue by vokkko** [Cheeun/CADyQ#9]
It's a nice work for SR ! I have met the issue that RuntimeError: Error(s) in loading state_dict for EDSR_CADyQ:
        Missing key(s) in state_dict: "body.9.weight", "body.9.bias". 
        Unexpected key(s) in state_dict: "body.10.bitsel1.quant_bit1.alpha",......when i use the command of test after i trained the model of EDSR for cadyq.
How can i solve this problem?

**Comment by vokkko** [comment]
Could you please tell me how many resblocks you set when you train the techer network for pams W8A8?

**Comment by Cheeun** [comment]
Hi, thanks for your interest in our work, and sorry for the delayed response!
For the second question, for EDSR, we used 16 resblocks for both teacher and student network.
And for your first question, could you check if you have used the bash file (_test_cadyq_image.sh_ or _test_cadyq_patch.sh_) for test?

**Comment by vokkko** [comment]
Thanks for your reply. I have sovled the problem.:)
